# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tG_UWsnBPHpZeKbhBHVkTKeHn6NMpPJ-
"""

# server.py
import torch
import copy

class Server:
    def __init__(self, global_model):
        self.global_model = global_model

    def aggregate_fedavg(self, client_states, client_sizes):
        """
        FedAvg aggregation:
        z^t = sum_k |D_k| z_k / sum_k |D_k|
        """
        new_state = copy.deepcopy(client_states[0])
        total_data = sum(client_sizes)

        for key in new_state.keys():
            new_state[key] = sum(
                client_states[i][key] * client_sizes[i]
                for i in range(len(client_states))
            ) / total_data

        self.global_model.load_state_dict(new_state)