# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tG_UWsnBPHpZeKbhBHVkTKeHn6NMpPJ-
"""

# train_fedavg.py
import torch
from model import SimpleNet
from client import Client
from server import Server

def sample_clients(clients, fraction=1.0):
    num = int(len(clients) * fraction)
    return torch.randperm(len(clients))[:num]

def train_fedavg(
    clients,
    global_model,
    rounds=10,
    local_epochs=1,
    fraction=1.0
):
    server = Server(global_model)

    for t in range(rounds):
        print(f"\n--- Round {t+1} ---")

        selected_ids = sample_clients(clients, fraction)
        client_states = []
        client_sizes = []

        for i in selected_ids:
            client = clients[i]
            client.set_weights(server.global_model)
            state, size = client.local_update(local_epochs)
            client_states.append(state)
            client_sizes.append(size)

        server.aggregate_fedavg(client_states, client_sizes)

    return server.global_model